### ISSUE TITLE
Can't initialize a new project

### ISSUE THREAD

**Issue by wezter96** [bidah/universal-medusa#4]
I run into the following issue when trying to initialize a project with:
npx create-universal-medusa-app ecom

After entering a username and password for postgres I get this after a while:

TypeError: Cannot read properties of undefined (reading 'host')
    at getForDbName (/Users/me/.npm/_npx/c1289c1a219c5807/node_modules/create-universal-medusa-app/dist/index.js:42:84136)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getDbClientAndCredentials (/Users/me/.npm/_npx/c1289c1a219c5807/node_modules/create-universal-medusa-app/dist/index.js:42:82790)
    at async run (/Users/me/.npm/_npx/c1289c1a219c5807/node_modules/create-universal-medusa-app/dist/index.js:42:80738)

Node.js v18.17.1

Let me know if you need any more info or if you happen to know why I might get this issue 😄

**Comment by wezter96** [comment]
Seems like it was an issue with my postgres installation, seems to work now
